### ISSUE TITLE
Texture warning for extendedseating:block/foot

### ISSUE THREAD

**Issue by Xyphenore** [alexandsr/CreateInteriorsMod#2]
**Describe the bug**

A warning is printed for the texture 'extendedseating:block/foot'.

The warning from the console:

'Texture extendedseating:block/foot with size 8x8 limits mip level from 4 to 3'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.

**Additional context**
- Mod version: 0.1 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by alexandsr** [comment]
Fixed in the latest release. Thanks for your issue report!
